export const texts = {
  en: {
    nav: {
      home: "Home",
      hajj: "Hajj",
      umrah: "Umrah",
      live: "Live",
      qibla: "Qibla",
      tasbi: "Tasbi",
      tools: "Tools",
      historical: "Historical Places",
      hospitals: "Hospitals",
      hotels: "Hotels",
      lostFound: "Lost & Found",
      donate: "Donate",
      contact: "Contact",
      admin: "Admin",
    },
    homeTitle: "Your complete Hajj & Umrah platform",
    homeDesc: "Beautiful, multilingual and fully manageable from admin.",
  },
  bn: {
    nav: {
      home: "হোম",
      hajj: "হজ",
      umrah: "উমরাহ",
      live: "লাইভ",
      qibla: "কিবলা",
      tasbi: "তাসবি",
      tools: "টুলস",
      historical: "ঐতিহাসিক স্থান",
      hospitals: "হাসপাতাল",
      hotels: "হোটেল",
      lostFound: "হারানো ও পাওয়া",
      donate: "ডোনেট",
      contact: "যোগাযোগ",
      admin: "অ্যাডমিন",
    },
    homeTitle: "আপনার পূর্ণাঙ্গ হজ ও উমরাহ প্ল্যাটফর্ম",
    homeDesc: "সুন্দর, বহু-ভাষার এবং অ্যাডমিন থেকে সম্পূর্ণ পরিচালনাযোগ্য।",
  },
  ar: {
    nav: {
      home: "الرئيسية",
      hajj: "الحج",
      umrah: "العمرة",
      live: "البث المباشر",
      qibla: "القبلة",
      tasbi: "التسبيح",
      tools: "الأدوات",
      historical: "الأماكن التاريخية",
      hospitals: "المستشفيات",
      hotels: "الفنادق",
      lostFound: "المفقودات",
      donate: "التبرع",
      contact: "اتصل",
      admin: "الإدارة",
    },
    homeTitle: "منصتك الكاملة للحج والعمرة",
    homeDesc: "واجهة جميلة ومتعددة اللغات ويمكن التحكم بها بالكامل من لوحة الإدارة.",
  },
};